stages:
  - test
  - deploy

services:
  - docker:dind

image: docker:stable

variables:
  APP_NAME: jazzband

before_script:
  - docker info
  - apk add --update py-pip make npm
  - pip install docker-compose

test:
  script:
    - cp .env-dist .env
    - make test

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://$APP_NAME.co/
  only:
    - master
  script:
    - git-push ssh://dokku@websushi.org:22/$APP_NAME
  when: manual
