image: docker:latest

stages:
  - test
  - deploy

services:
  - docker:dind

cache:
  paths:
    - .cache/pip

variables:
  APP_NAME: jazzband
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test:
  stage: test
  before_script:
    - docker info
    - apk add --update py-pip make npm build-base python2-dev libffi-dev openssl-dev
    - pip install docker-compose
  script:
    - cp .env-dist .env
    - make test

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://$APP_NAME.co/
  only:
    - master
  script:
    - git-push ssh://dokku@websushi.org:22/$APP_NAME
  when: manual
