image: docker:latest

stages:
  - test
  - deploy

services:
  - docker:dind

variables:
  APP_NAME: jazzband
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

test:
  stage: test
  before_script:
    - docker info
    - apk add --update make npm
    - curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - cp .env-dist .env
    - make test

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://$APP_NAME.co/
  only:
    - master
  script:
    - git-push ssh://dokku@websushi.org:22/$APP_NAME
  when: manual
