stages:
  - test
  - deploy

services:
  - docker:dind

variables:
  APP_NAME: jazzband
  DOCKER_DRIVER: overlay2

test:
  before_script:
    - docker info
    - apk add --update py-pip make npm build-base python2-dev
    - pip install docker-compose
  image: docker:latest
  script:
    - cp .env-dist .env
    - make test

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://$APP_NAME.co/
  only:
    - master
  script:
    - git-push ssh://dokku@websushi.org:22/$APP_NAME
  when: manual
