version: '2'
services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"

  redis:
    image: redis:latest

  app:
    build: .
    # pass those two into the environment
    environment:
      - FLASK_APP=jazzband/app.py
      - FLASK_DEBUG=1
    # but also response the .env file for the rest
    env_file:
      - .env
    volumes:
      - .:/app

  web:
    extends:
      service: app
    command: honcho start -f Procfile.dev web
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    links:
      - db
      - redis

  worker:
    extends:
      service: app
    command: honcho start -f Procfile.dev worker
    links:
      - db
      - redis
