name: Push
on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push
      uses: vitalyliber/dokku-github-action@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        HOST: ${{ secrets.DOKKU_HOST }}
        PROJECT: ${{ secrets.DOKKU_APPNAME }}
