name: Deploy
on:
  push:
    tags:
    - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Test
      run: make ci

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v1
    - name: Push
      uses: vitalyliber/dokku-github-action@master
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        HOST: ${{ secrets.DOKKU_HOST }}
        PROJECT: ${{ secrets.DOKKU_APPNAME }}
